stages:
  - build
  - test
  - deploy

Instalar dependencias:
  image: python:3.7-slim
  stage: build
  script:
    - pip install -r requirements.txt

Ejecutar pruebas:
  image: python:3.7-slim
  stage: test
  script:
    - pytest