stages:
  - build
  - test
  - deploy

Instalar dependencias:
  image: python:3.7-slim
  stage: build
  before_script:
    - pip install virtualenv
    - virtualenv venv
  script:
    - env
    - source venv/bin/activate
    - pip install -r requirements.txt
  artifacts:
    paths:
      - venv

Ejecutar pruebas:
  image: python:3.7-slim
  stage: test
  script:
    - source venv/bin/activate
    - pytest

Desplegar app:
  image: ruby:2.3-slim
  stage: deploy
  script:
    - gem install dpl --pre
    - dpl --provider=heroku --api_key=$HEROKU_API --app=gitlab-python-ci-edteam














